name: Prepare Go environment
description: Setup Go, download Go modules and install binary dependencies
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        cache: false
    - name: Find GOPATH
      id: find-gopath
      run: echo "result=$(go env GOPATH)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Cache GOPATH
      id: cache-gopath
      uses: actions/cache@v3
      with:
        path: ${{ steps.find-gopath.outputs.result }}
        key: go-environment.go-mod-${{ hashFiles('**/go.mod', '**/go.sum') }}
    - name: Download Go modules
      if: steps.cache-gopath.outputs.cache-hit != 'true'
      run: go mod download
      shell: bash
    - name: Cache tools
      id: cache-tools
      uses: actions/cache@v3
      with:
        path: tools/bin
        key: go-environment.tools-go-mod-${{ hashFiles('**/tools/go.mod', '**/tools/go.sum') }}
    - name: Install tools
      if: steps.cache-tools.outputs.cache-hit != 'true'
      run: make tools
      shell: bash