run:
  go: '1.22'
  timeout: 3m
  issues-exit-code: 1

issues:
  max-issues-per-linter: 50
  max-same-issues: 10

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - gocognit
    - gocritic
    - gocyclo
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - noctx
    - revive
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/klwxsrx/go-service-template
  gosec:
    excludes:
      - G601
  importas:
    alias:
      # common aliases
      - pkg: github.com/Masterminds/squirrel
        alias: sq
      - pkg: github.com/klwxsrx/go-service-template/pkg/(\w+)
        alias: pkg$1
      - pkg: github.com/klwxsrx/go-service-template/pkg/(\w+)/(\w+)
        alias: pkg$1$2
      - pkg: github.com/klwxsrx/go-service-template/pkg/(\w+)/(\w+)/(\w+)
        alias: pkg$1$2$3
      - pkg: github.com/klwxsrx/go-service-template/internal/pkg/(\w+)
        alias: common$1
      - pkg: github.com/klwxsrx/go-service-template/internal/pkg/(\w+)/(\w+)
        alias: common$1$2
      - pkg: github.com/klwxsrx/go-service-template/internal/pkg/(\w+)/(\w+)/(\w+)
        alias: common$1$2$3
      # domain-specific aliases
      - pkg: github.com/klwxsrx/go-service-template/internal/(duck)/(\w+)
        alias: $1$2
      - pkg: github.com/klwxsrx/go-service-template/internal/(duck)/(\w+)/(\w+)
        alias: $1$2$3
      - pkg: github.com/klwxsrx/go-service-template/internal/(duck)/(\w+)/(\w+)/(\w+)
        alias: $1$2$3$4
      - pkg: github.com/klwxsrx/go-service-template/internal/(duck)/(\w+)/(\w+)/(\w+)/(\w+)
        alias: $1$2$3$4$5
  unused:
    field-writes-are-uses: false