run:
  timeout: 3m
  issues-exit-code: 1

issues:
  max-issues-per-linter: 50
  max-same-issues: 10

linters:
  enable:
    - bodyclose
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - importas
    - misspell
    - noctx
    - revive
    - unconvert
    - unparam

linters-settings:
  goimports:
    local-prefixes: github.com/klwxsrx/go-service-template
  importas:
    alias:
      # common aliases
      - pkg: github.com/Masterminds/squirrel
        alias: sq
      - pkg: github.com/klwxsrx/go-service-template/pkg/(\w+)
        alias: pkg$1
      - pkg: github.com/klwxsrx/go-service-template/pkg/(\w+)/(\w+)
        alias: pkg$1$2
      - pkg: github.com/klwxsrx/go-service-template/internal/pkg/(\w+)
        alias: common$1
      - pkg: github.com/klwxsrx/go-service-template/internal/pkg/(\w+)/(\w+)
        alias: common$1$2
      # domain aliases
      - pkg: github.com/klwxsrx/go-service-template/internal/(duck)/(\w+)
        alias: $1$2
      - pkg: github.com/klwxsrx/go-service-template/internal/(duck)/(\w+)/(\w+)
        alias: $1$2$3
      - pkg: github.com/klwxsrx/go-service-template/internal/(duck)/(\w+)/(\w+)/(\w+)
        alias: $1$2$3$4