pre-commit:
  piped: true
  skip:
    - merge
    - rebase
  commands:
    go-codegen:
      priority: 1
      run: make codegen && git diff --quiet
    go-checks:
      priority: 2
      run: make check
    go-build:
      priority: 3
      run: make build-clean build
post-checkout:
  parallel: true
  commands:
    git-hooks:
      run: make git-hooks