services:

  user-service:
    build:
      dockerfile: docker/user-service/Dockerfile
      context: .
    container_name: go-service-template-user-service
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SQL_ADDRESS=postgresql:5432
      - PULSAR_ADDRESS=apache-pulsar:6650

  user-profile-service:
    build:
      dockerfile: docker/user-profile-service/Dockerfile
      context: .
    container_name: go-service-template-user-profile-service
    depends_on:
      user-service:
        condition: service_started
      postgresql:
        condition: service_healthy
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - SQL_ADDRESS=postgresql:5432
      - PULSAR_ADDRESS=apache-pulsar:6650
      - USER_SERVICE_URL=http://user-service:8080

  user-profile-worker:
    build:
      dockerfile: docker/user-profile-worker/Dockerfile
      context: .
    container_name: go-service-template-user-profile-worker
    depends_on:
      user-service:
        condition: service_started
      postgresql:
        condition: service_healthy
      apache-pulsar:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SQL_ADDRESS=postgresql:5432
      - PULSAR_ADDRESS=apache-pulsar:6650
      - USER_SERVICE_URL=http://user-service:8080

  message-outbox-worker:
    build:
      dockerfile: docker/message-outbox-worker/Dockerfile
      context: .
    container_name: go-service-template-message-outbox-worker
    depends_on:
      postgresql:
        condition: service_healthy
      apache-pulsar:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SQL_ADDRESS=postgresql:5432
      - PULSAR_ADDRESS=apache-pulsar:6650

  postgresql:
    image: postgres:16
    container_name: go-service-template-postgresql
    volumes:
      - postgresql-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: go_service_template
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "go_service_template" ]
      interval: 10s
      timeout: 3s
      retries: 6
    restart: unless-stopped

  apache-pulsar:
    image: apachepulsar/pulsar:4.0.0
    container_name: go-service-template-apache-pulsar
    volumes:
      - apache-pulsar-data:/pulsar/data:rw
    ports:
      - "6650:6650"
    entrypoint: [ "bin/pulsar", "standalone" ]
    healthcheck:
      test: [ "CMD", "/pulsar/bin/pulsar-admin", "brokers", "healthcheck" ]
      interval: 30s
      timeout: 3s
      retries: 10
    restart: unless-stopped

volumes:
  postgresql-data:
    name: go-service-template-postgresql-data
  apache-pulsar-data:
    name: go-service-template-apache-pulsar-data