version: "3.8"
services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    hostname: postgresql
    volumes:
      - postgresql-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: go_service_template
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "go_service_template" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  apache-pulsar:
    image: apachepulsar/pulsar:2.10.2
    container_name: apache-pulsar
    hostname: apache-pulsar
    volumes:
      - apache-pulsar-data:/pulsar/data:rw
    ports:
      - "6650:6650"
    entrypoint: [ "bin/pulsar", "standalone" ]
    healthcheck:
      test: /pulsar/bin/pulsar-admin brokers healthcheck
      interval: 30s
      timeout: 5s
      retries: 20
    restart: unless-stopped
volumes:
  postgresql-data:
  apache-pulsar-data: