version: "3.9"
services: # TODO: add apps

  duck-postgresql:
    image: postgres:16
    container_name: postgresql
    hostname: postgresql
    volumes:
      - duck-postgresql-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: go_service_template
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "go_service_template" ]
      interval: 10s
      timeout: 3s
      retries: 6
    restart: unless-stopped

  duck-apache-pulsar:
    image: apachepulsar/pulsar:3.2.2
    container_name: apache-pulsar
    hostname: apache-pulsar
    volumes:
      - duck-apache-pulsar-data:/pulsar/data:rw
    ports:
      - "6650:6650"
    entrypoint: [ "bin/pulsar", "standalone" ]
    healthcheck:
      test: [ "CMD", "/pulsar/bin/pulsar-admin", "brokers", "healthcheck" ]
      interval: 30s
      timeout: 3s
      retries: 10
    restart: unless-stopped

volumes:
  duck-postgresql-data:
  duck-apache-pulsar-data: