#!/bin/sh

# Ignore if make rule doesn't exist
make git-pre-commit --recon > /dev/null || exit 0

# Ignore rebase and merge state
git rev-parse -q --verify REBASE_HEAD && exit 0
git rev-parse -q --verify MERGE_HEAD && exit 0

# Run make rule
RESULT="$(make git-pre-commit)"
if [[ $? != 0 ]]; then
  echo "${RESULT}"
  exit 1
fi
