#!/bin/sh

# Check make rule exist
make git-pre-commit --recon > /dev/null
if [[ $? != 0 ]]; then
  exit 0
fi

# Run make rule
RESULT="$(make git-pre-commit)"
if [[ $? != 0 ]]; then
  echo "${RESULT}"
  exit 1
fi
