name: Build Docker images
on:
  push:
    branches: [ master ]

jobs:
  go-lint:
    name: Lint Go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3

  go-test:
    name: Run Go unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Run tests
        run: make test

  go-build:
    name: Build Go images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - application: duck
            image-file: duck.image.tar
          - application: duckhandler
            image-file: duckhandler.image.tar
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Build application
        run: make bin/${{ matrix.application }}
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          file: docker/${{ matrix.application }}/Dockerfile
          context: .
          outputs: type=docker,dest=docker/${{ matrix.image-file }}
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.image-file }}
          path: docker/${{ matrix.image-file }}

  docker-push:
    name: Push Docker images
    needs:
      - go-lint
      - go-test
      - go-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image-tag: klwxsrx/duck-service
            image-file: duck.image.tar
          - image-tag: klwxsrx/duck-event-handler
            image-file: duckhandler.image.tar
    steps:
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.image-file }}
          path: /tmp
      - name: Import Docker image
        run: docker image import /tmp/${{ matrix.image-file }} ${{ matrix.image-tag }}:${{ github.ref_name }}
      - name: Push Docker image
        run: docker push ${{ matrix.image-tag }}:${{ github.ref_name }}
