name: Build Docker images
on:
  push:
    branches: [ master ]

jobs:
  go-prepare-env:
    name: Prepare Go environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare Go environment
        uses: ./.github/actions/prepare-go-environment

  go-lint:
    name: Lint Go code
    needs: go-prepare-env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare Go environment
        uses: ./.github/actions/prepare-go-environment
      - name: Run golangci-lint
        run: make lint

  go-test:
    name: Run Go tests
    needs: go-prepare-env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare Go environment
        uses: ./.github/actions/prepare-go-environment
      - name: Run tests
        run: make test

  go-arch:
    name: Validate Go architecture
    needs: go-prepare-env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare Go environment
        uses: ./.github/actions/prepare-go-environment
      - name: Run go-cleanarch
        run: make arch

  go-build:
    name: Build Go images
    needs: go-prepare-env
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - application: user-service
            image-file: user-service.image.tar
          - application: user-profile-service
            image-file: user-profile-service.image.tar
          - application: user-profile-worker
            image-file: user-profile-worker.image.tar
          - application: message-outbox-worker
            image-file: message-outbox-worker.image.tar
          - application: idk-cleaner-task
            image-file: idk-cleaner-task.image.tar
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare Go environment
        uses: ./.github/actions/prepare-go-environment
      - name: Build application
        run: make bin/${{ matrix.application }}
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          file: docker/${{ matrix.application }}/Dockerfile
          context: .
          outputs: type=docker,dest=docker/${{ matrix.image-file }}
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.image-file }}
          path: docker/${{ matrix.image-file }}

  docker-push:
    name: Push Docker images
    needs:
      - go-arch
      - go-lint
      - go-test
      - go-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image-tag: klwxsrx/go-service-template-user-service
            image-file: user-service.image.tar
          - image-tag: klwxsrx/go-service-template-user-profile-service
            image-file: user-profile-service.image.tar
          - image-tag: klwxsrx/go-service-template-user-profile-worker
            image-file: user-profile-worker.image.tar
          - image-tag: klwxsrx/go-service-template-message-outbox-worker
            image-file: message-outbox-worker.image.tar
          - image-tag: klwxsrx/go-service-template-idk-cleaner-task
            image-file: idk-cleaner-task.image.tar
    steps:
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.image-file }}
          path: /tmp
      - name: Import Docker image
        run: docker image import /tmp/${{ matrix.image-file }} ${{ matrix.image-tag }}:${{ github.ref_name }}
      - name: Push Docker image
        run: docker push ${{ matrix.image-tag }}:${{ github.ref_name }}
